apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: prom-node-exporter
spec:
  selector:
    matchLabels:
      name: prom-node-exporter
  template:
    metadata:
      name:  prom-node-exporter
      labels:
        name: prom-node-exporter
      annotations:
        prometheus.io.scrape: "true"
    spec:
      hostPID: true
      containers:
      - name:  prom-node-exporter
        image: prom/node-exporter
        securityContext:
          privileged: true
        ports:
        - containerPort: 9100
